version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_APP_BACKEND_API=http://backend:8081
      - VITE_APP_FRONTEND_URL=http://localhost:8080
    volumes:
      - ./src:/app
    command: npm run dev