version: '3.9'

services:
  fast:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8081:8080"
    volumes:
      - ./src:/app
    environment:
      - ENVIRONMENT=development
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
